# Base config
baseurl:              
host:                 localhost
port:                 8080

# Publishing
markdown:             kramdown
markdown_ext:         md
encoding:             utf-8
highlighter:          rouge
permalink:            pretty
lsi:                  false
incremental:          false
strict_front_matter:  false

# Markdown config
kramdown: 
  auto_ids:           true
  entity_output:      as_char
  toc_levels:         1..6
  smart_quotes:       lsquo,rsquo,ldquo,rdquo
  input:              GFM
  hard_wrap:          false
  footnote_nr:        1

# Default front matter
defaults: 
  - values:           # defaul for all pages
      layout:         default
      lang:           hu
  - scope:
      type: subjects
    values:
      layout: subject
  - scope:
      type: projects
    values:
      layout: project
  - scope:
      type: courses
    values:
      layout: course

# Collections
collections: 
  subjects:    
    permalink:      /:name:output_ext
    output:         true
  projects:
    permalink:      /projekt/:name:output_ext
    output:         true
  courses:
    permalink:      /:path:output_ext
    output:         true
  materials:
    permalink:      /tananyag/:name:output_ext

# Plugins
plugins:
  - jekyll-toc